// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGhXlUT_q6DBwVmYTcrodW98O8sVELDUs',
    appId: '1:921230168488:web:fa583470382ca41d660d9d',
    messagingSenderId: '921230168488',
    projectId: 'drink-duel-extreme',
    authDomain: 'drink-duel-extreme.firebaseapp.com',
    storageBucket: 'drink-duel-extreme.appspot.com',
    measurementId: 'G-Q80RZHWJQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA45yo7fDpISMC4Cvsawo9XijUmNF8C2vo',
    appId: '1:921230168488:android:8122a1910d675ff9660d9d',
    messagingSenderId: '921230168488',
    projectId: 'drink-duel-extreme',
    storageBucket: 'drink-duel-extreme.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDEarPfc8417CW7s0JXI8AjZs0BBxK0KE',
    appId: '1:921230168488:ios:d8dce670e4ad9e2a660d9d',
    messagingSenderId: '921230168488',
    projectId: 'drink-duel-extreme',
    storageBucket: 'drink-duel-extreme.appspot.com',
    iosBundleId: 'com.example.drinkDuelsExtreme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDEarPfc8417CW7s0JXI8AjZs0BBxK0KE',
    appId: '1:921230168488:ios:277c6db4da18249b660d9d',
    messagingSenderId: '921230168488',
    projectId: 'drink-duel-extreme',
    storageBucket: 'drink-duel-extreme.appspot.com',
    iosBundleId: 'com.example.drinkDuelsExtreme.RunnerTests',
  );
}
